### ISSUE TITLE
why traefik 8080 console cannot visit ?

### ISSUE THREAD

**Issue by autherlj** [patrickeasters/traefik-k8s-tls-example#2]
I according you config and final everything working fine but when I visit traefik web console, seems it cannot monitoring

**Comment by patrickeasters** [comment]
The `traefik.toml` file I included did not come with an entrypoint for the [api/dashboard](https://docs.traefik.io/configuration/api/) enabled.  In your `traefik.toml` file, try adding something like this under your entrypoints section in order to force it to listen on port 8080 for the dashboard:
```
[entryPoints]
  [entryPoints.traefik]
  address = ":8080"
```

**Comment by autherlj** [comment]
okey, tks!
